##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50,60])

arr[[0,2,4]]

array([10, 30, 50])

You can do this fancy indexing in 2D Matrix aswell

In [6]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
matrix[[0,1],[1,2]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([2, 7])

##Conditional Selection
Find values based on conditions or replace them.

In [9]:

arr = np.array([5,12,18,7,30])
arr > 10
arr[arr > 10]
np.where(arr>10)

(array([1, 2, 4]),)

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [11]:
arr = np.array([42,5,18,23])
np.sort(arr)

array([ 5, 18, 23, 42])

##Concatenation & Stacking

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concat([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [13]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A


array([[1, 2],
       [3, 4]])

In [14]:
B

array([[5, 6],
       [7, 8]])

In [15]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [17]:
np.concat([A,B])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])