##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

Now lets see the 2D indexing aswell

In [3]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[1,1]

np.int64(5)

In [5]:
arr[0,1]

np.int64(2)

Now we can also do the slicing lets see the **slicing in 1D**

In [6]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

1D slicing was really easy now lets see the **slicing in 2D**

There is one more thing known as **Boolean indexing**

In [8]:
a[0:3]

[1, 2, 3]

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [12]:
arr = np.array([5,10,20,30,40])
print(arr>12)

[False False  True  True  True]


## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [16]:
a = np.arange(1,31).reshape(5,6)
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])